### PR TITLE
Do some pythonic code cleanups

### PR DESCRIPTION
**Pull request by AmirHmZz**
This PR corrects some parts of python code in order to follow some points:

- Replace `X == None` with `X is None` which is more standard and faster
- Replace not `X is None` with `X is not None` according to **PEP 8: E714**
- Replace `not  A == B` with `A != B` .The difference between these two is the first one makes python to do 2 operation (Checking equality and then `not` the result)  while the second one just consist of one operation (Checking non-equality)
- Remove unnecessary parenthesis when assigning multiple values to multiple variables ( Replace `(a,b) = something` with `a,b = something` )

### CODE REVIEW

**Comment by AmirHmZz** [comment]
There are also more code cleanups and speed ups. There are lots of things need to be changed specially the project structure.

**Comment by cirospaciari** [comment]
> There are also more code cleanups and speed ups. There are lots of things need to be changed specially the project structure.

Just send me all this, thanks a lot for this clean ups I will see the changes and accept this ASAP after I get out my Full time job

**Comment by AmirHmZz** [comment]
Should I send these or open PR? I think it's better to make project structure standard before other things.
For example moving Enums and Option classes other python files and …
There are lots of things we should talk about. What's your opinion about opening a discussion and continue there?

**Comment by cirospaciari** [comment]
> Should I send these or open PR? I think it's better to make project structure standard before other things. For example moving Enums and Option classes to other python files and … There are lots of things we should talk about. What's your opinion about opening a discussion and continue there?

Lets open it! This project started this year and a lot of things are added, like i said before in the past this project need a major refactor before v1.0.0 but we still in v0.0.1 beta-3 so we need to talk about changes now and move forward in the right way.

**Review by cirospaciari — APPROVED** [review]

**Pull request merged**
