### PR TITLE
Converts Option classes from normal classes into python `dataclasses`

### PR DESCRIPTION
**Pull request by AmirHmZz**
This PR : 

- Converts Option classes from normal classes into python `dataclasses`
- Remove duplicate setting of `key_file_name`
- Fix some typos in RuntimeError messages
- Some more code cleanups in return statements of functions

### CODE REVIEW

**Comment by AmirHmZz** [comment]
I think it would be better to squash all commits into one commit and then merge.

**Comment by cirospaciari** [comment]
> I think it would be better to squash all commits into one commit and then merge.

I will

**Review by cirospaciari — APPROVED** [review]

**Comment by cirospaciari** [comment]
Thanks again for the contribuition :mechanical_arm:

**Comment by cirospaciari** [comment]
I will just remove the NoneType because:
https://hg.python.org/cpython/rev/918bbee3a545

**Comment by AmirHmZz** [comment]
Whoops. https://docs.python.org/3/library/types.html?highlight=types#types.NoneType
NoneType is just added in python3.10 but that import can be easily replaced with this line :
```NoneType = type(None)```

**Comment by cirospaciari** [comment]
> Whoops. https://docs.python.org/3/library/types.html?highlight=types#types.NoneType NoneType is just added in python3.10 but that import can be easily replaced with this line : `NoneType = type(None)`

Yes! i already did it! thanks!

**Pull request merged**
