### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
**Description**

This PR fixes typos found via `codespell -S .mypy_cache -L falsy`

### CODE REVIEW

**Comment by cirospaciari** [comment]
Thanks! I will test and merge this PR this week ❤️🦾

**Comment by cirospaciari** [comment]
Just an update This contribution will be merged and added before the first release on PyPi. Thanks again for your support

**Comment by cirospaciari** [comment]
@kianmeng Can you update our branch and re-run the same codespell again? i will merge it as soon TechEmPower accepts my last update (so the benchmarks dont break)

**Comment by kianmeng** [comment]
@cirospaciari Done. Check again.

**Comment by cirospaciari** [comment]
merged with next, so when TechEmPower approves i can merge in main branch and release the next version

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
